/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateRecurringGrantRequestDonor {
    /** The first name of the donor */
    firstName?: string;
    /** The last name of the donor */
    lastName?: string;
    /** The email address of the donor */
    email?: string;
    /** The phone number of the donor */
    phone?: string;
}
