/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the grant:
 *
 * - Initiated: The grant has been initiated and is ready to be processed
 * - Completed: The grant has been completed
 */
export type GrantsUpdateRequestStatus = "Initiated" | "Completed";

export const GrantsUpdateRequestStatus = {
    Initiated: "Initiated",
    Completed: "Completed",
} as const;
