/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../../../index";

export interface GrantsCreateRequestDonor {
    /** The first name of the donor. Maximum length: 255 characters. */
    firstName?: string;
    /** The last name of the donor. Maximum length: 255 characters. */
    lastName?: string;
    /** The email address of the donor. Maximum length: 255 characters. */
    email?: string;
    /** The phone number of the donor. Maximum length: 255 characters. */
    phone?: string;
    address?: Chariot.GrantAddress;
}
