/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";

export const UnintegratedGrantsUpdateRequestStatus: core.serialization.Schema<
    serializers.UnintegratedGrantsUpdateRequestStatus.Raw,
    Chariot.UnintegratedGrantsUpdateRequestStatus
> = core.serialization.enum_(["Initiated", "Completed"]);

export declare namespace UnintegratedGrantsUpdateRequestStatus {
    type Raw = "Initiated" | "Completed";
}
