/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";

export const GetTokenResponse: core.serialization.ObjectSchema<
    serializers.GetTokenResponse.Raw,
    Chariot.GetTokenResponse
> = core.serialization.object({
    accessToken: core.serialization.property("access_token", core.serialization.string().optional()),
    tokenType: core.serialization.property("token_type", core.serialization.string().optional()),
    expiresIn: core.serialization.property("expires_in", core.serialization.number().optional()),
});

export declare namespace GetTokenResponse {
    interface Raw {
        access_token?: string | null;
        token_type?: string | null;
        expires_in?: number | null;
    }
}
