/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";

export const GrantsUpdateRequestStatus: core.serialization.Schema<
    serializers.GrantsUpdateRequestStatus.Raw,
    Chariot.GrantsUpdateRequestStatus
> = core.serialization.enum_(["Initiated", "Completed"]);

export declare namespace GrantsUpdateRequestStatus {
    type Raw = "Initiated" | "Completed";
}
