/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";
import { Grant } from "../../../types/Grant";

export const GrantsListResponse: core.serialization.ObjectSchema<
    serializers.GrantsListResponse.Raw,
    Chariot.GrantsListResponse
> = core.serialization.object({
    results: core.serialization.list(Grant).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace GrantsListResponse {
    interface Raw {
        results?: Grant.Raw[] | null;
        nextPageToken?: string | null;
    }
}
