/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";
import { RecurringGrant } from "../../../types/RecurringGrant";

export const ListRecurringGrantsResponse: core.serialization.ObjectSchema<
    serializers.ListRecurringGrantsResponse.Raw,
    Chariot.ListRecurringGrantsResponse
> = core.serialization.object({
    results: core.serialization.list(RecurringGrant).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListRecurringGrantsResponse {
    interface Raw {
        results?: RecurringGrant.Raw[] | null;
        nextPageToken?: string | null;
    }
}
