/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../../../../index";

/**
 * @example
 *     {}
 */
export interface GrantsUpdateRequest {
    /**
     * The status of the grant:
     *   * Initiated: The grant has been initiated and is ready to be processed
     *   * Completed: The grant has been completed
     */
    status?: Chariot.GrantsUpdateRequestStatus;
    /**
     * The date and time the grant was acknowledged by the nonprofit.
     * This is useful for nonprofits to indicate when they have received and processed the grant.
     * Expressed in ISO 8601 format.
     */
    acknowledgedAt?: Date;
}
