/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { RecurringGrantsCreateRequestDonor } from "../../types/RecurringGrantsCreateRequestDonor";
import { GrantAddress } from "../../../../types/GrantAddress";

export const RecurringGrantsCreateRequest: core.serialization.Schema<
    serializers.RecurringGrantsCreateRequest.Raw,
    Chariot.RecurringGrantsCreateRequest
> = core.serialization.object({
    workflowSessionId: core.serialization.string(),
    amount: core.serialization.number(),
    applicationFeeAmount: core.serialization.number().optional(),
    donor: RecurringGrantsCreateRequestDonor.optional(),
    address: GrantAddress.optional(),
});

export declare namespace RecurringGrantsCreateRequest {
    interface Raw {
        workflowSessionId: string;
        amount: number;
        applicationFeeAmount?: number | null;
        donor?: RecurringGrantsCreateRequestDonor.Raw | null;
        address?: GrantAddress.Raw | null;
    }
}
