/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { RecurringGrantsCreateRequestDonor } from "../../types/RecurringGrantsCreateRequestDonor";

export const RecurringGrantsCreateRequest: core.serialization.Schema<
    serializers.RecurringGrantsCreateRequest.Raw,
    Chariot.RecurringGrantsCreateRequest
> = core.serialization.object({
    workflowSessionId: core.serialization.string(),
    amount: core.serialization.number(),
    applicationFeeAmount: core.serialization.number().optional(),
    donor: RecurringGrantsCreateRequestDonor.optional(),
    note: core.serialization.string().optional(),
    designation: core.serialization.string().optional(),
});

export declare namespace RecurringGrantsCreateRequest {
    interface Raw {
        workflowSessionId: string;
        amount: number;
        applicationFeeAmount?: number | null;
        donor?: RecurringGrantsCreateRequestDonor.Raw | null;
        note?: string | null;
        designation?: string | null;
    }
}
