/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { EventCategory } from "../../../../types/EventCategory";

export const EventSubscriptionsCreateRequest: core.serialization.Schema<
    serializers.EventSubscriptionsCreateRequest.Raw,
    Chariot.EventSubscriptionsCreateRequest
> = core.serialization.object({
    url: core.serialization.string(),
    category: EventCategory,
    signingSecret: core.serialization.string().optional(),
});

export declare namespace EventSubscriptionsCreateRequest {
    interface Raw {
        url: string;
        category: EventCategory.Raw;
        signingSecret?: string | null;
    }
}
