/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { EventSubscriptionsUpdateRequestStatus } from "../../types/EventSubscriptionsUpdateRequestStatus";

export const EventSubscriptionsUpdateRequest: core.serialization.Schema<
    serializers.EventSubscriptionsUpdateRequest.Raw,
    Chariot.EventSubscriptionsUpdateRequest
> = core.serialization.object({
    status: EventSubscriptionsUpdateRequestStatus.optional(),
});

export declare namespace EventSubscriptionsUpdateRequest {
    interface Raw {
        status?: EventSubscriptionsUpdateRequestStatus.Raw | null;
    }
}
