/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Chariot from "../index";

export class PreconditionFailedError extends errors.ChariotError {
    constructor(body: Chariot.Error_) {
        super({
            message: "PreconditionFailedError",
            statusCode: 412,
            body: body,
        });
        Object.setPrototypeOf(this, PreconditionFailedError.prototype);
    }
}
