/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";
import { Event } from "../../../types/Event";

export const EventsListResponse: core.serialization.ObjectSchema<
    serializers.EventsListResponse.Raw,
    Chariot.EventsListResponse
> = core.serialization.object({
    results: core.serialization.list(Event).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace EventsListResponse {
    interface Raw {
        results?: Event.Raw[] | null;
        nextPageToken?: string | null;
    }
}
