/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class ChariotTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, ChariotTimeoutError.prototype);
    }
}
