/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { NonprofitsCreateRequestUser } from "../../types/NonprofitsCreateRequestUser";

export const NonprofitsCreateRequest: core.serialization.Schema<
    serializers.NonprofitsCreateRequest.Raw,
    Chariot.NonprofitsCreateRequest
> = core.serialization.object({
    user: NonprofitsCreateRequestUser,
    ein: core.serialization.string(),
    preferredName: core.serialization.string().optional(),
    picture: core.serialization.string().optional(),
    website: core.serialization.string().optional(),
});

export declare namespace NonprofitsCreateRequest {
    interface Raw {
        user: NonprofitsCreateRequestUser.Raw;
        ein: string;
        preferredName?: string | null;
        picture?: string | null;
        website?: string | null;
    }
}
