/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";
import { EventSubscription } from "../../../types/EventSubscription";

export const EventSubscriptionsListResponse: core.serialization.ObjectSchema<
    serializers.EventSubscriptionsListResponse.Raw,
    Chariot.EventSubscriptionsListResponse
> = core.serialization.object({
    results: core.serialization.list(EventSubscription).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace EventSubscriptionsListResponse {
    interface Raw {
        results?: EventSubscription.Raw[] | null;
        nextPageToken?: string | null;
    }
}
