/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";

export const EventSubscriptionsUpdateRequestStatus: core.serialization.Schema<
    serializers.EventSubscriptionsUpdateRequestStatus.Raw,
    Chariot.EventSubscriptionsUpdateRequestStatus
> = core.serialization.enum_(["active", "disabled", "deleted"]);

export declare namespace EventSubscriptionsUpdateRequestStatus {
    type Raw = "active" | "disabled" | "deleted";
}
