/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         nonprofit: "6af3f58e-7a80-4997-8259-770c033d7d3a",
 *         suborganization: "c00d1aa2-09ab-4e76-8461-7ac34578a70c"
 *     }
 */
export interface ConnectsCreateRequest {
    /**
     * The unique identifier (ID) for the nonprofit.
     * The format should be a v4 UUID according to RFC 4122.
     * This can be found by calling the /v1/nonprofit/{ein} API endpoint.
     */
    nonprofit: string;
    /**
     * The unique identifier (ID) for the suborganization within the nonprofit.
     * The format should be a v4 UUID according to RFC 4122.
     * This can be found by calling the /v1/nonprofit/{ein} API endpoint.
     */
    suborganization?: string;
    /** A human readable name of the Connect, optional. */
    name?: string;
    /** A map of arbitrary string keys and values to store information about the object. */
    metadata?: Record<string, string>;
}
