/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../index";

export interface ContributionFeeDetail {
    /**
     * The name of the party charging the fee. This is an informational field.
     * If you need to differentiate between fees charged by different parties, you should use the `feeType` field.
     */
    name: string;
    /** The fee contribution amount expressed in units of cents */
    amount: number;
    /**
     * This indicates the source of a fee contribution.
     *
     * - chariot: Chariot's processing fee
     * - daf: The DAF's processing fee
     * - fundraising_application: The fundraising application's processing fee
     */
    feeType?: Chariot.ContributionFeeDetailFeeType;
}
