/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This indicates the source of a fee contribution.
 *
 * - chariot: Chariot's processing fee
 * - daf: The DAF's processing fee
 * - fundraising_application: The fundraising application's processing fee
 */
export type ContributionFeeDetailFeeType = "chariot" | "daf" | "fundraising_application";

export const ContributionFeeDetailFeeType = {
    Chariot: "chariot",
    Daf: "daf",
    FundraisingApplication: "fundraising_application",
} as const;
