/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A Donor-Advised Fund, or `DAF` for short, is a special-purpose, tax-advantaged charitable account.
 * For more information, please see the [IRS website](https://www.irs.gov/charities-non-profits/charitable-organizations/donor-advised-funds) for a full description.
 * In the case that a DAF is supported, a donor will be able to initiate a grant directly through DAFpay.
 */
export interface Daf {
    /** The unique identifier for this object. */
    id: string;
    /** A human readable name for the DAF. */
    orgName: string;
    /** The first address line. */
    address: string;
    /** The second address line. */
    address2: string;
    /** The city name for the address. */
    city: string;
    /** The state name for the address. */
    state: string;
    /** The zipcode for the address. */
    zip: string;
    /** A flag to indicate if this DAF is supported by DAFpay. */
    supported: boolean;
    /** The minimum grant amount in cents allowed for this DAF. */
    minimumGrantAmount: number;
    /** A flag to indicate if the institution is down. */
    institutionDown: boolean;
}
