/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A DAF represents Donor-Advised Funds which are connected with Chariot. These may be integrated (able to authenticate through Chariot) or unintegrated.
 */
export interface Daf {
    /** The unique identifier for this object. */
    id: string;
    /** A human readable name for the DAF. */
    orgName: string;
    /** The first address line. */
    address: string;
    /** The second address line. */
    address2: string;
    /** The city name for the address. */
    city: string;
    /** The state name for the address. */
    state: string;
    /** The zipcode for the address. */
    zip: string;
    /** A flag to indicate if this DAF is supported by Chariot. */
    supported: boolean;
    /** The minimum grant amount allowed for this DAF. */
    minimumGrantAmount: number;
    /** A flag to indicate if the institution is down. */
    institutionDown: boolean;
}
