/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the event subscription.
 * This indicates if we'll send notifications to this subscription
 *
 * - active: subscription is active and events will be delivered normally
 * - disabled: subscription is temporarily disabled and events will not be delivered
 * - deleted: subscription has been deleted and events will not be delivered
 * - requires_attention: subscription has been disabled due to delivery failures and events will not be delivered
 */
export type EventSubscriptionStatus = "active" | "disabled" | "deleted" | "requires_attention";

export const EventSubscriptionStatus = {
    Active: "active",
    Disabled: "disabled",
    Deleted: "deleted",
    RequiresAttention: "requires_attention",
} as const;
