/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../index";

/**
 * Webhooks are event notifications we send to you by HTTPS POST requests.
 * Event Subscriptions are how you configure your application to listen for them.
 */
export interface EventSubscription {
    /** The unique identifier for the event subscription */
    id?: string;
    /** The date and time the event subscription was created */
    createdAt?: Date;
    status?: Chariot.EventSubscriptionStatus;
    /** The webhook url where we'll send notifications. */
    url: string;
    category?: Chariot.EventCategory;
}
