/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The category of the event. This is useful for filtering events.
 */
export type EventCategory =
    | "grant.created"
    | "grant.updated"
    | "unintegrated_grant.created"
    | "unintegrated_grant.updated";

export const EventCategory = {
    GrantCreated: "grant.created",
    GrantUpdated: "grant.updated",
    UnintegratedGrantCreated: "unintegrated_grant.created",
    UnintegratedGrantUpdated: "unintegrated_grant.updated",
} as const;
