/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GrantAddress {
    /** Address line 1 (e.g. street, PO Box, or company name) */
    line1?: string;
    /** Address line 2 (e.g. apartment, suite, unit, or building) */
    line2?: string;
    /** City, district, suburb, town, or village. */
    city?: string;
    /** State, county, province, or region */
    state?: string;
    /** ZIP or postal code */
    postalCode?: string;
}
