/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../index";

/**
 * A Grant represents a successfully initiated grant request with a Donor Advised Fund. Grants are created when a person interacts with an instance of Chariot Connect and successfully submits a grant and completes the workflow. There can be many grants associated with a Connect object and therefore a Nonprofit.
 */
export interface Grant {
    /** The unique identifier for the object */
    id: string;
    /** Often referred to as the "Chariot ID", this is the ID that will be included in the payment from the DAF provider. */
    userFriendlyId?: string;
    /** The tracking ID for the grant */
    trackingId?: string;
    /** ID of the Connect Workflow Session associated with this grant */
    workflowSessionId: string;
    /** ID of the donor advised fund */
    fundId: string;
    /** ID of the grant associated with the donor advised fund */
    externalGrantId?: string;
    /** Time when this object was created; expressed in ISO 8601 format */
    createdAt?: Date;
    /** Time when this object was last updated; expressed in ISO 8601 format */
    updatedAt?: Date;
    /** The grant amount expressed in units of whole cents */
    amount: number;
    /** The status of the grant */
    status?: string;
    /** The fee detail of the grant */
    feeDetail?: Chariot.GrantFeeDetail;
    /** A map of arbitrary string keys and values to store information about the object */
    metadata?: Record<string, string>;
    /** The donor's first name */
    firstName?: string;
    /** The donor's last name */
    lastName?: string;
    /** The donor's phone number */
    phone?: string;
    /** The donor's email */
    email?: string;
    /** An note inputted by the user at submisson */
    note?: string;
    /** The list of grant statuses for this grant */
    statuses?: Chariot.GrantStatus[];
    /**
     * The payment channel for the grant. This is useful to know how the grant will be sent.
     * The payment channel will be one of the following:
     *
     * - dafpay_network: Grant will be sent to the DAFPay Network 501(c)(3) non-profit organization (EIN: 93-1372175). The DAFPay Network will then review and process the grant and send the funds to the intended recipient.
     * - direct: Grant will be sent directly to the intended recipient.
     */
    paymentChannel?: Chariot.GrantPaymentChannel;
    address?: Chariot.GrantAddress;
}
