/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the grant. To see a description of each status, see the "Grant Statuses" section of the Chariot documentation.
 */
export type GrantStatusStatus = "Initiated" | "Completed" | "Canceled";

export const GrantStatusStatus = {
    Initiated: "Initiated",
    Completed: "Completed",
    Canceled: "Canceled",
} as const;
