/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GrantAddress {
    /** Address line 1 (e.g. street, PO Box, or company name). Maximum length: 255 characters. */
    line1?: string;
    /** Address line 2 (e.g. apartment, suite, unit, or building). Maximum length: 255 characters. */
    line2?: string;
    /** City, district, suburb, town, or village.. Maximum length: 255 characters. */
    city?: string;
    /** State, county, province, or region. Maximum length: 255 characters. */
    state?: string;
    /** ZIP or postal code. Maximum length: 255 characters. */
    postalCode?: string;
}
