/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../index";

export interface GrantStatus {
    /** The unique identifier for the object */
    id: string;
    /** Time when this object was created; expressed in ISO 8601 format */
    createdAt: Date;
    /** The status of the grant. To see a description of each status, see the "Grant Statuses" section of the Chariot documentation. */
    status: Chariot.GrantStatusStatus;
    /** The user comment for the update */
    comment?: string;
}
