/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../index";

/**
 * The fee detail of the grant
 */
export interface GrantFeeDetail {
    /** The total fee amount expressed in units of cents */
    total?: number;
    /** The list of fee contributions for this grant */
    contributions?: Chariot.ContributionFeeDetail[];
}
