/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OauthScope =
    /**
     * create a nonprofit and user */
    | "create:nonprofits"
    /**
     * read all nonprofits */
    | "read:nonprofits"
    /**
     * create any connect, principle does not need to be associated with nonprofit */
    | "create:connects"
    /**
     * read all connects for a nonprofit */
    | "read:connects"
    /**
     * create a grant from a workflow session */
    | "create:grants"
    /**
     * read grants */
    | "read:grants"
    /**
     * update grants */
    | "update:grants"
    /**
     * read events */
    | "read:events"
    /**
     * create event subscriptions */
    | "create:event_subscriptions"
    /**
     * read event subscriptions */
    | "read:event_subscriptions"
    /**
     * update event subscriptions */
    | "update:event_subscriptions";

export const OauthScope = {
    CreateNonprofits: "create:nonprofits",
    ReadNonprofits: "read:nonprofits",
    CreateConnects: "create:connects",
    ReadConnects: "read:connects",
    CreateGrants: "create:grants",
    ReadGrants: "read:grants",
    UpdateGrants: "update:grants",
    ReadEvents: "read:events",
    CreateEventSubscriptions: "create:event_subscriptions",
    ReadEventSubscriptions: "read:event_subscriptions",
    UpdateEventSubscriptions: "update:event_subscriptions",
} as const;
