/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../index";

/**
 * A RecurringGrant represents a successfully initiated recurring grant request with a Donor Advised Fund.
 * RecurringGrants are created when a person interacts with an instance of Chariot Connect and successfully submits a recurring grant and completes the workflow.
 * On creation, each RecurringGrant object will also have a Grant object created to represent the first grant of the recurring grant.
 * There can be many grants associated with the same recurring grant.
 */
export interface RecurringGrant {
    /** The unique identifier for the object */
    id: string;
    /** The tracking ID for the grant */
    trackingId?: string;
    /** ID of the Connect Workflow Session associated with this grant */
    workflowSessionId: string;
    /** ID of the donor advised fund */
    fundId: string;
    /** How often the DAF provider will submit the recurring grant. At the moment, monthly is the only supported frequency. */
    frequency: "MONTHLY";
    /** ID of the grant associated with the donor advised fund */
    externalGrantId?: string;
    /** Time when this object was created; expressed in ISO 8601 format */
    createdAt?: Date;
    /** Time when this object was last updated; expressed in ISO 8601 format */
    updatedAt?: Date;
    /** The grant amount expressed in units of whole cents */
    amount: number;
    /** The donor's first name */
    firstName?: string;
    /** The donor's last name */
    lastName?: string;
    /** The donor's phone number */
    phone?: string;
    /** The donor's email */
    email?: string;
    /** An note inputted by the user at submisson */
    note?: string;
    address?: Chariot.GrantAddress;
}
