/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../index";

/**
 * A suborganization represents an organization that is under the umbrella of a parent EIN.
 * This is common for nonprofits that have multiple chapters or locations or operate as a fiscal sponsor.
 */
export interface Suborganization {
    /** The unique identifier for the object. */
    id: string;
    /** The registered name of the suborganization */
    name: string;
    /** The preferred name of the suborganization. This is the name that shows up on the nonprofit's dashboard and Connect modal. This is useful for nonprofits that are known by a different name to donors and don't use their IRS registered name publicly. */
    preferredName?: string;
    address?: Chariot.Address;
    /** The URI of the nonprofit's logo */
    picture?: string;
    /** The URL of the nonprofit's website */
    website?: string;
    /** Time when this object was created. Expressed in ISO 8601 format. */
    createdAt?: Date;
    /** Time when this object was last updated. Expressed in ISO 8601 format. */
    updatedAt?: Date;
}
