/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the unintegrated grant.
 * To see a description of each status, see the "Unintegrated Grant Statuses" section of the Chariot documentation.
 */
export type UnintegratedGrantStatus = "Unknown" | "Initiated" | "Completed" | "Canceled";

export const UnintegratedGrantStatus = {
    Unknown: "Unknown",
    Initiated: "Initiated",
    Completed: "Completed",
    Canceled: "Canceled",
} as const;
