/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Chariot from "../../../../api/index";
import * as core from "../../../../core";
import { Daf } from "../../../types/Daf";

export const DaFsListResponse: core.serialization.ObjectSchema<
    serializers.DaFsListResponse.Raw,
    Chariot.DaFsListResponse
> = core.serialization.object({
    results: core.serialization.list(Daf).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace DaFsListResponse {
    interface Raw {
        results?: Daf.Raw[] | null;
        nextPageToken?: string | null;
    }
}
