/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { UnintegratedGrantsUpdateRequestStatus } from "../../types/UnintegratedGrantsUpdateRequestStatus";

export const UnintegratedGrantsUpdateRequest: core.serialization.Schema<
    serializers.UnintegratedGrantsUpdateRequest.Raw,
    Chariot.UnintegratedGrantsUpdateRequest
> = core.serialization.object({
    status: UnintegratedGrantsUpdateRequestStatus.optional(),
    acknowledgedAt: core.serialization.date().optional(),
});

export declare namespace UnintegratedGrantsUpdateRequest {
    interface Raw {
        status?: UnintegratedGrantsUpdateRequestStatus.Raw | null;
        acknowledgedAt?: string | null;
    }
}
