/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";

export const ConnectsCreateRequest: core.serialization.Schema<
    serializers.ConnectsCreateRequest.Raw,
    Omit<Chariot.ConnectsCreateRequest, "nonprofit" | "suborganization">
> = core.serialization.object({
    name: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
});

export declare namespace ConnectsCreateRequest {
    interface Raw {
        name?: string | null;
        metadata?: Record<string, string> | null;
    }
}
