/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../../../../index";

/**
 * @example
 *     {
 *         user: {
 *             email: "ben.give@co.com"
 *         },
 *         ein: "043567500"
 *     }
 */
export interface NonprofitsCreateRequest {
    user: Chariot.NonprofitsCreateRequestUser;
    /** The US federal employer identification number (Tax ID); unique on the system */
    ein: string;
    /** The preferred name of the nonprofit organization. This is the name that shows up on the nonprofit's dashboard and Connect modal. This is useful for nonprofits that are known by a different name to donors and don't use their IRS registered name publicly. */
    preferredName?: string;
    /** The URI of the nonprofit's logo */
    picture?: string;
    /** The URL of the nonprofit's website */
    website?: string;
}
