/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../../../../index";

/**
 * @example
 *     {}
 */
export interface EventSubscriptionsUpdateRequest {
    /**
     * The status of the event subscription:
     *   * active: The event subscription is active and events will be delivered
     *   * disabled: The event subscription is temporarily disabled and events will not be delivered
     *   * deleted: The event subscription is permanently deleted and events will not be delivered
     */
    status?: Chariot.EventSubscriptionsUpdateRequestStatus;
}
