/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../../../../index";

/**
 * @example
 *     {
 *         url: "https://example.com/webhook",
 *         category: Chariot.EventCategory.GrantCreated
 *     }
 */
export interface EventSubscriptionsCreateRequest {
    /** The webhook url where we'll send notifications. */
    url: string;
    category: Chariot.EventCategory;
    /**
     * The key that will be used to sign webhooks.
     * If no value is passed, a random string will be used as default.
     * This is necessary to verify that the webhook is coming from Chariot.
     * While this parameter is optional, it is highly recommended to pass a value
     * for the secret and implement webhook signature verification.
     */
    signingSecret?: string;
}
