/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const Address: core.serialization.ObjectSchema<serializers.Address.Raw, Chariot.Address> =
    core.serialization.object({
        city: core.serialization.string(),
        country: core.serialization.string(),
        line1: core.serialization.string(),
        line2: core.serialization.string().optional(),
        postalCode: core.serialization.string(),
        state: core.serialization.string(),
    });

export declare namespace Address {
    interface Raw {
        city: string;
        country: string;
        line1: string;
        line2?: string | null;
        postalCode: string;
        state: string;
    }
}
