/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";
import { ContributionFeeDetailFeeType } from "./ContributionFeeDetailFeeType";

export const ContributionFeeDetail: core.serialization.ObjectSchema<
    serializers.ContributionFeeDetail.Raw,
    Chariot.ContributionFeeDetail
> = core.serialization.object({
    name: core.serialization.string(),
    amount: core.serialization.number(),
    feeType: ContributionFeeDetailFeeType.optional(),
});

export declare namespace ContributionFeeDetail {
    interface Raw {
        name: string;
        amount: number;
        feeType?: ContributionFeeDetailFeeType.Raw | null;
    }
}
