/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const Daf: core.serialization.ObjectSchema<serializers.Daf.Raw, Chariot.Daf> = core.serialization.object({
    id: core.serialization.string(),
    orgName: core.serialization.string(),
    address: core.serialization.string(),
    address2: core.serialization.string(),
    city: core.serialization.string(),
    state: core.serialization.string(),
    zip: core.serialization.string(),
    supported: core.serialization.boolean(),
    minimumGrantAmount: core.serialization.number(),
    institutionDown: core.serialization.boolean(),
});

export declare namespace Daf {
    interface Raw {
        id: string;
        orgName: string;
        address: string;
        address2: string;
        city: string;
        state: string;
        zip: string;
        supported: boolean;
        minimumGrantAmount: number;
        institutionDown: boolean;
    }
}
