/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, Chariot.Error_> =
    core.serialization.object({
        timestamp: core.serialization.string(),
        code: core.serialization.number(),
        error: core.serialization.string(),
        message: core.serialization.string(),
    });

export declare namespace Error_ {
    interface Raw {
        timestamp: string;
        code: number;
        error: string;
        message: string;
    }
}
