/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";
import { EventCategory } from "./EventCategory";

export const Event: core.serialization.ObjectSchema<serializers.Event.Raw, Chariot.Event> = core.serialization.object({
    id: core.serialization.string().optional(),
    category: EventCategory.optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    associatedObjectId: core.serialization.property("associated_object_id", core.serialization.string().optional()),
    associatedObjectType: core.serialization.property("associated_object_type", core.serialization.string().optional()),
});

export declare namespace Event {
    interface Raw {
        id?: string | null;
        category?: EventCategory.Raw | null;
        created_at?: string | null;
        associated_object_id?: string | null;
        associated_object_type?: string | null;
    }
}
