/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const EventSubscriptionStatus: core.serialization.Schema<
    serializers.EventSubscriptionStatus.Raw,
    Chariot.EventSubscriptionStatus
> = core.serialization.enum_(["active", "disabled", "deleted", "requires_attention"]);

export declare namespace EventSubscriptionStatus {
    type Raw = "active" | "disabled" | "deleted" | "requires_attention";
}
