/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const EventCategory: core.serialization.Schema<serializers.EventCategory.Raw, Chariot.EventCategory> =
    core.serialization.enum_([
        "grant.created",
        "grant.updated",
        "unintegrated_grant.created",
        "unintegrated_grant.updated",
    ]);

export declare namespace EventCategory {
    type Raw = "grant.created" | "grant.updated" | "unintegrated_grant.created" | "unintegrated_grant.updated";
}
