/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";
import { GrantFeeDetail } from "./GrantFeeDetail";
import { GrantStatus } from "./GrantStatus";
import { GrantPaymentChannel } from "./GrantPaymentChannel";
import { GrantAddress } from "./GrantAddress";

export const Grant: core.serialization.ObjectSchema<serializers.Grant.Raw, Chariot.Grant> = core.serialization.object({
    id: core.serialization.string(),
    userFriendlyId: core.serialization.string().optional(),
    trackingId: core.serialization.string().optional(),
    workflowSessionId: core.serialization.string(),
    fundId: core.serialization.string(),
    externalGrantId: core.serialization.string().optional(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
    amount: core.serialization.number(),
    status: core.serialization.string().optional(),
    feeDetail: GrantFeeDetail.optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    firstName: core.serialization.string().optional(),
    lastName: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    note: core.serialization.string().optional(),
    statuses: core.serialization.list(GrantStatus).optional(),
    paymentChannel: GrantPaymentChannel.optional(),
    address: GrantAddress.optional(),
});

export declare namespace Grant {
    interface Raw {
        id: string;
        userFriendlyId?: string | null;
        trackingId?: string | null;
        workflowSessionId: string;
        fundId: string;
        externalGrantId?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        amount: number;
        status?: string | null;
        feeDetail?: GrantFeeDetail.Raw | null;
        metadata?: Record<string, string> | null;
        firstName?: string | null;
        lastName?: string | null;
        phone?: string | null;
        email?: string | null;
        note?: string | null;
        statuses?: GrantStatus.Raw[] | null;
        paymentChannel?: GrantPaymentChannel.Raw | null;
        address?: GrantAddress.Raw | null;
    }
}
