/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const GrantStatusStatus: core.serialization.Schema<
    serializers.GrantStatusStatus.Raw,
    Chariot.GrantStatusStatus
> = core.serialization.enum_(["Initiated", "Completed", "Canceled"]);

export declare namespace GrantStatusStatus {
    type Raw = "Initiated" | "Completed" | "Canceled";
}
