/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const GrantPaymentChannel: core.serialization.Schema<
    serializers.GrantPaymentChannel.Raw,
    Chariot.GrantPaymentChannel
> = core.serialization.enum_(["dafpay_network", "direct"]);

export declare namespace GrantPaymentChannel {
    type Raw = "dafpay_network" | "direct";
}
