/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const OauthScope: core.serialization.Schema<serializers.OauthScope.Raw, Chariot.OauthScope> =
    core.serialization.enum_([
        "create:nonprofits",
        "read:nonprofits",
        "create:connects",
        "read:connects",
        "create:grants",
        "read:grants",
        "update:grants",
        "read:events",
        "create:event_subscriptions",
        "read:event_subscriptions",
        "update:event_subscriptions",
    ]);

export declare namespace OauthScope {
    type Raw =
        | "create:nonprofits"
        | "read:nonprofits"
        | "create:connects"
        | "read:connects"
        | "create:grants"
        | "read:grants"
        | "update:grants"
        | "read:events"
        | "create:event_subscriptions"
        | "read:event_subscriptions"
        | "update:event_subscriptions";
}
