/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";
import { GrantAddress } from "./GrantAddress";

export const RecurringGrant: core.serialization.ObjectSchema<serializers.RecurringGrant.Raw, Chariot.RecurringGrant> =
    core.serialization.object({
        id: core.serialization.string(),
        trackingId: core.serialization.string().optional(),
        workflowSessionId: core.serialization.string(),
        fundId: core.serialization.string(),
        frequency: core.serialization.stringLiteral("MONTHLY"),
        externalGrantId: core.serialization.string().optional(),
        createdAt: core.serialization.date().optional(),
        updatedAt: core.serialization.date().optional(),
        amount: core.serialization.number(),
        firstName: core.serialization.string().optional(),
        lastName: core.serialization.string().optional(),
        phone: core.serialization.string().optional(),
        email: core.serialization.string().optional(),
        note: core.serialization.string().optional(),
        address: GrantAddress.optional(),
    });

export declare namespace RecurringGrant {
    interface Raw {
        id: string;
        trackingId?: string | null;
        workflowSessionId: string;
        fundId: string;
        frequency: "MONTHLY";
        externalGrantId?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        amount: number;
        firstName?: string | null;
        lastName?: string | null;
        phone?: string | null;
        email?: string | null;
        note?: string | null;
        address?: GrantAddress.Raw | null;
    }
}
