/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";
import { Address } from "./Address";

export const Suborganization: core.serialization.ObjectSchema<
    serializers.Suborganization.Raw,
    Chariot.Suborganization
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    preferredName: core.serialization.string().optional(),
    address: Address.optional(),
    picture: core.serialization.string().optional(),
    website: core.serialization.string().optional(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
});

export declare namespace Suborganization {
    interface Raw {
        id: string;
        name: string;
        preferredName?: string | null;
        address?: Address.Raw | null;
        picture?: string | null;
        website?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
    }
}
