/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";

export const UnintegratedGrantStatus: core.serialization.Schema<
    serializers.UnintegratedGrantStatus.Raw,
    Chariot.UnintegratedGrantStatus
> = core.serialization.enum_(["Unknown", "Initiated", "Completed", "Canceled"]);

export declare namespace UnintegratedGrantStatus {
    type Raw = "Unknown" | "Initiated" | "Completed" | "Canceled";
}
