/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Chariot from "../../api/index";
import * as core from "../../core";
import { UnintegratedGrantStatus } from "./UnintegratedGrantStatus";
import { GrantAddress } from "./GrantAddress";

export const UnintegratedGrant: core.serialization.ObjectSchema<
    serializers.UnintegratedGrant.Raw,
    Chariot.UnintegratedGrant
> = core.serialization.object({
    id: core.serialization.string(),
    userFriendlyId: core.serialization.string().optional(),
    workflowSessionId: core.serialization.string(),
    fundId: core.serialization.string(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
    amount: core.serialization.number(),
    status: UnintegratedGrantStatus.optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    firstName: core.serialization.string().optional(),
    lastName: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    address: GrantAddress.optional(),
    note: core.serialization.string().optional(),
    paymentChannel: core.serialization.stringLiteral("offline").optional(),
});

export declare namespace UnintegratedGrant {
    interface Raw {
        id: string;
        userFriendlyId?: string | null;
        workflowSessionId: string;
        fundId: string;
        createdAt?: string | null;
        updatedAt?: string | null;
        amount: number;
        status?: UnintegratedGrantStatus.Raw | null;
        metadata?: Record<string, string> | null;
        firstName?: string | null;
        lastName?: string | null;
        phone?: string | null;
        email?: string | null;
        address?: GrantAddress.Raw | null;
        note?: string | null;
        paymentChannel?: "offline" | null;
    }
}
