/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Chariot from "../../../../index";

/**
 * @example
 *     {
 *         workflowSessionId: "workflowSessionId",
 *         amount: 1.1
 *     }
 */
export interface RecurringGrantsCreateRequest {
    /**
     * The identifier of the donor's DAFpay Workflow Session.
     * See [Capturing Grant Intents](/guides/dafpay/integrating-dafpay/integration#capturing-grant-intents) for how to get this value from the DAFpay `CHARIOT_SUCCESS` event.
     */
    workflowSessionId: string;
    /**
     * The final grant amount in cents that will be processed by Chariot and submitted to the DAF for recurring gifts.
     * This amount must be in whole dollar increments (rounded to the nearest hundred) as currently
     * all DAFs only accept whole dollar grants.
     */
    amount: number;
    /**
     * This parameter specifies the fee your platform plans to take from the first grant in cents.
     * This is a fee in addition to Chariot's processing fee. With application fees,
     * Chariot collects the fee you determine from the nonprofit and passes it to your platform.
     * Please note that platform fees are only taken when the grant is successfully received by the Nonprofit.
     * The sum of Chariot's fee and the applicationFeeAmount cannot exceed 5% of the grant's amount.
     * If the 5% limit is exceeded, a 400 error will be returned.
     */
    applicationFeeAmount?: number;
    donor?: Chariot.RecurringGrantsCreateRequestDonor;
    /** A note the donor wants to send to the nonprofit. Maximum length: 400 characters. */
    note?: string;
    /**
     * The designation to include on the grant. If this is left blank, "Where needed most" will be used.
     * Note that including a custom designation may cause the grant approval process to take longer.
     * Designations over 100 characters will be truncated.
     */
    designation?: string;
}
