/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NonprofitsCreateRequestUser {
    /** The email address for the nonprofit account contact */
    email: string;
    /** The phone number for the nonprofit account contact */
    phone?: string;
    /** The first name of the nonprofit account contact */
    firstName?: string;
    /** The last name of the nonprofit account contact */
    lastName?: string;
}
