/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ChariotEnvironment = {
    Production: "https://api.givechariot.com",
    Sandbox: "https://sandboxapi.givechariot.com",
} as const;

export type ChariotEnvironment = typeof ChariotEnvironment.Production | typeof ChariotEnvironment.Sandbox;
