/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChariotEnvironmentUrls {
    api: string;
}

export const ChariotEnvironment = {
    Production: {
        api: "https://api.givechariot.com",
    },
    Sandbox: {
        api: "https://sandboxapi.givechariot.com",
    },
} as const;

export type ChariotEnvironment = typeof ChariotEnvironment.Production | typeof ChariotEnvironment.Sandbox;
