/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ChariotEnvironment = {
    Sandbox: "https://sandboxapi.givechariot.com",
    Production: "https://api.givechariot.com",
} as const;

export type ChariotEnvironment = typeof ChariotEnvironment.Sandbox | typeof ChariotEnvironment.Production;
