/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { CreateRecurringGrantRequestDonor } from "../../types/CreateRecurringGrantRequestDonor";
import { GrantAddress } from "../../../../types/GrantAddress";

export const CreateRecurringGrantRequest: core.serialization.Schema<
    serializers.CreateRecurringGrantRequest.Raw,
    Chariot.CreateRecurringGrantRequest
> = core.serialization.object({
    workflowSessionId: core.serialization.string(),
    amount: core.serialization.number(),
    applicationFeeAmount: core.serialization.number().optional(),
    donor: CreateRecurringGrantRequestDonor.optional(),
    address: GrantAddress.optional(),
});

export declare namespace CreateRecurringGrantRequest {
    interface Raw {
        workflowSessionId: string;
        amount: number;
        applicationFeeAmount?: number | null;
        donor?: CreateRecurringGrantRequestDonor.Raw | null;
        address?: GrantAddress.Raw | null;
    }
}
