/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { GrantsUpdateRequestStatus } from "../../types/GrantsUpdateRequestStatus";

export const GrantsUpdateRequest: core.serialization.Schema<
    serializers.GrantsUpdateRequest.Raw,
    Chariot.GrantsUpdateRequest
> = core.serialization.object({
    status: GrantsUpdateRequestStatus.optional(),
    acknowledgedAt: core.serialization.date().optional(),
});

export declare namespace GrantsUpdateRequest {
    interface Raw {
        status?: GrantsUpdateRequestStatus.Raw | null;
        acknowledgedAt?: string | null;
    }
}
