/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Chariot from "../../../../../api/index";
import * as core from "../../../../../core";
import { GrantsCreateRequestDonor } from "../../types/GrantsCreateRequestDonor";

export const GrantsCreateRequest: core.serialization.Schema<
    serializers.GrantsCreateRequest.Raw,
    Chariot.GrantsCreateRequest
> = core.serialization.object({
    workflowSessionId: core.serialization.string(),
    amount: core.serialization.number(),
    applicationFeeAmount: core.serialization.number().optional(),
    donor: GrantsCreateRequestDonor.optional(),
    note: core.serialization.string().optional(),
    designation: core.serialization.string().optional(),
});

export declare namespace GrantsCreateRequest {
    interface Raw {
        workflowSessionId: string;
        amount: number;
        applicationFeeAmount?: number | null;
        donor?: GrantsCreateRequestDonor.Raw | null;
        note?: string | null;
        designation?: string | null;
    }
}
